baseURL = "https://nickgregorich.com/"
disqusShortname = ""
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = false
languageCode = "en"
pagination.pagerSize = 5
rssLimit = 10
theme = "hugo-texify3"
title = "Nick Gregorich"

[author]
name = "Nick Gregorich"
email = "blog@nickgregorich.com"

[taxonomies]
tags = "tags"
categories = "categories"

[params]
title="Nick Gregorich"
description = "Nerdy thoughts, from my brain to yours"
footnote = """
Powered by  <a class=link href=https://gohugo.io target=_blank rel=noopener>Hugo</a> | 
Theme is a <a class=link href=https://github.com/ngregorich/hugo-texify3 target=_blank rel=noopener>fork</a> of <a class=link href=https://github.com/michaelneuper/hugo-texify3 target=_blank rel=noopener>TeXify3</a>
"""
customCSS = []
customJS = []
dateFormat = "02 Jan 2006"
emphasisWithDots = false
toc = true
rootFontSize = "100%"
math = true
enableDuckDuckGoSearchBox = false
numberedSubtitles = true

  [params.commentEngine]
  code = """"""

  [params.buymeacoffee]
  code = """"""

  [params.sharingbuttons]
  facebook = false
  twitter = false
  email = false
  linkedin = false
  reddit = false
  whatsapp = false
  hackernews = false
  telegram = false
